include:
  - board: seeeduino_xiao_ble
    shield: cheapinov2_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: cheapinov2_right
# there is no settingsreset (needed) for the XIAO
